import {API_BASE,request,setCsrf} from './api.js';
import {esc,icon,button,empty,notice,roles,localDate,dateTime,toast,openModal,closeModal,download,list} from './ui.js';
import {demoData,DEMO_DATE} from './demo.js';
import {landing,scheduleView,roomsView,searchView,aboutView,roomDetail,eventDetail,events} from './views.js';
import {registryView,coordinatorView,allocationView,publishView,historyView,validationSummary} from './management.js';
import {schemas,fieldsHTML,parseRecord,blockHTML,labelOf} from './schema.js';

const app=document.querySelector('#app');
const state={apiBase:API_BASE,session:null,data:null,demo:false,route:'login',periodId:'',classId:'',date:localDate(),scheduleView:'day',query:'',entity:'rooms',allocFilter:'all',allocCourse:'',selectedMeetings:new Set(),validation:null,solverResult:null,comparison:null,loadedAt:null,loginError:'',busy:false};
let editing=null,importReport=null,loadSerial=0;
const routeNames={schedule:'Minha agenda',rooms:'Salas e localização',search:'Pesquisar',registry:'Cadastros',coordinator:'Necessidades das turmas',allocation:'Ensalamento',publish:'Publicação',history:'Histórico',about:'Sobre o projeto'};
const readOnlyRoutes=['schedule','rooms','search','about'];
const permittedRoutes=()=>state.session?.user?.role==='admin'?Object.keys(routeNames):state.session?.user?.role==='coordinator'?[...readOnlyRoutes,'coordinator','history']:readOnlyRoutes;
const prefKey=()=>`ensalamento:turma:${state.session?.user?.id}:${state.periodId}`;
function readPreference(){try{return localStorage.getItem(prefKey()) || '';}catch{return '';}}
function savePreference(id){state.classId=id;try{localStorage.setItem(prefKey(),id);}catch{toast('A turma foi selecionada, mas o navegador não permitiu guardar a preferência.');}}
function classesForPeriod(){return (state.data?.classes || []).filter(c=>c.period_id===state.periodId&&!['cancelled','closed'].includes(c.status));}
function needsOfficial(){return state.session?.user?.role==='coordinator'&&['schedule','rooms','search'].includes(activeRoute());}
function activeRoute(){const route=location.hash.slice(1).split('?')[0] || (state.session?.user?'schedule':'login');return route;}
function navigate(route){if(location.hash===`#${route}`){state.route=route;render();}else location.hash=route;}
function formError(form,error){const target=form.querySelector('.form-error');if(target){target.innerHTML=notice(error.message || String(error),'error');target.setAttribute('role','alert');target.scrollIntoView({block:'nearest'});}else toast(error.message || String(error),true);}
function shell(content){const user=state.session.user;const navigation=[['schedule','calendar'],['rooms','building'],['search','search'],...(user.role==='admin'?[['registry','grid'],['coordinator','users'],['allocation','layers'],['publish','shield'],['history','history']]:user.role==='coordinator'?[['coordinator','users'],['history','history']]:[]),['about','info']];return `<div class="app-shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#schedule"><span class="brand-mark" aria-hidden="true">E</span><span>Ensalamento<small>Seu espaço acadêmico</small></span></a><nav class="main-nav" aria-label="Navegação principal">${navigation.map(([route,name])=>`<a class="nav-item ${state.route===route?'active':''}" href="#${route}" ${state.route===route?'aria-current="page"':''}>${icon(name)}${routeNames[route]}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="user-card"><span class="avatar" aria-hidden="true">${esc((user.name || 'U').slice(0,2).toUpperCase())}</span><span><strong>${esc(user.name)}</strong><small>${roles[user.role] || 'Visitante'}</small></span></div>${button(icon('logout')+(state.demo?' Sair do exemplo':' Sair'),'logout','ghost small')}<p class="academic-note">Projeto acadêmico · ${esc(window.ENSALAMENTO_CONFIG?.YEAR || 2026)}<br>Não é uma publicação institucional.</p></div></aside><div class="workspace"><header class="topbar"><div class="flex"><button class="btn ghost icon-only mobile-menu" data-action="menu" aria-label="Abrir navegação" aria-controls="sidebar" aria-expanded="false">${icon('menu')}</button><span class="breadcrumb">Ensalamento / <strong>${routeNames[state.route] || ''}</strong></span></div><div class="topbar-right"><span class="status-line"><span class="dot"></span>${state.data?.mode==='draft'?'Área de planejamento':'Consulta oficial'}</span><label class="sr-only" for="period-select">Período letivo</label><select class="period-select" id="period-select">${(state.data?.periods || []).map(p=>`<option value="${esc(p.id)}" ${p.id===state.periodId?'selected':''}>${esc(p.name)}</option>`).join('') || '<option value="">Sem período publicado</option>'}</select>${button(icon('refresh'),'refresh','ghost icon-only','aria-label="Atualizar dados"')}</div></header>${state.demo?`<div class="demo-banner"><span><strong>Exemplo de consulta.</strong> Dados fictícios e data ilustrativa; não é a versão oficial de uma instituição.</span>${button('Voltar à entrada','logout','ghost small')}</div>`:state.data?.demo_data?'<div class="demo-banner"><strong>Desenvolvimento local · dados fictícios para teste. Sem autenticação institucional.</strong></div>':''}<main id="main" class="page-content" tabindex="-1">${content}<div class="update-foot">${icon('refresh')}Última consulta: ${dateTime(state.loadedAt)}${state.data?.published_version?` · Versão ${esc(state.data.published_version.number)}`:''}</div></main></div></div>`;}
function render(){state.route=activeRoute();if(state.route==='about'&&!state.session?.user){app.innerHTML=`<div class="public-shell"><header class="public-header"><a class="brand" href="#login"><span class="brand-mark">E</span>Ensalamento</a><a href="#login" class="btn secondary">Voltar à entrada</a></header><main id="main">${aboutView()}</main></div>`;return;}
  if(!state.session?.user || state.route==='login'){app.innerHTML=landing(state);return;}
  if(!state.data){app.innerHTML='<main id="main" class="loading-screen"><span class="spinner"></span><p>Carregando seus horários…</p></main>';return;}
  if(!permittedRoutes().includes(state.route)){state.route=state.session.user.role==='coordinator'?'coordinator':'schedule';history.replaceState(null,'',`#${state.route}`);}
  const renderers={schedule:scheduleView,rooms:roomsView,search:searchView,about:aboutView,registry:registryView,coordinator:coordinatorView,allocation:allocationView,publish:publishView,history:historyView};
  app.innerHTML=shell(renderers[state.route](state));
}
async function loadData({quiet=false,resetPeriod=false}={}){if(state.demo){render();return;}const serial=++loadSerial;const params=new URLSearchParams();if(state.periodId&&!resetPeriod)params.set('period_id',state.periodId);if(needsOfficial())params.set('view','published');const param=params.size?'?'+params.toString():'';try{const data=await request('/api/bootstrap'+param);if(serial!==loadSerial)return;if(state.data?.revision!==data.revision){state.validation=null;state.comparison=null;}state.data=data;state.periodId=data.period_id || data.periods?.[0]?.id || '';state.session.user=data.user;setCsrf(data.csrf_token);state.loadedAt=new Date().toISOString();const saved=readPreference();state.classId=classesForPeriod().some(c=>c.id===saved)?saved:'';state.selectedMeetings=new Set([...state.selectedMeetings].filter(id=>data.meetings.some(m=>m.id===id)));render();if(!quiet&&state.session.user.role==='student'&&!state.classId&&classesForPeriod().length)chooseClass();}catch(error){if(error.status===401){state.session.user=null;state.data=null;navigate('login');}else{toast(error.message,true);if(!quiet&&!state.data){state.loginError=error.message;navigate('login');}}}}
async function mutate(path,payload={}){if(state.demo)throw new Error('O exemplo público permite somente consulta.');const result=await request(path,{method:'POST',body:{...payload,revision:state.data.revision}});state.validation=null;state.comparison=null;await loadData({quiet:true});return result;}
function chooseClass(){const classes=classesForPeriod();openModal('Escolha e confirme sua turma',`<p>A escolha personaliza a consulta neste navegador para o seu usuário e período. Você poderá alterá-la depois.</p><label class="field mb">Buscar por código, curso, turno ou turma<input type="search" id="class-search" placeholder="Digite parte do código ou nome"></label><form id="choose-class-form"><div id="class-options">${classes.map(c=>{const course=state.data.courses.find(x=>x.id===c.course_id);return `<label class="selection-card" data-class-option data-search="${esc([c.code,c.name,c.shift,course?.name].join(' ').toLocaleLowerCase('pt-BR'))}"><input name="class_id" type="radio" required value="${esc(c.id)}" ${c.id===state.classId?'checked':''}><span><h3>${esc(c.code)}</h3><p>${esc(c.name)} · ${esc(course?.name)} · ${esc(c.shift || '')}</p></span></label>`;}).join('') || empty('Nenhuma turma disponível','Aguarde a publicação de turmas para o período.')}</div><p id="class-search-empty" hidden>Nenhuma turma encontrada. Tente outra busca ou contate a coordenação.</p><div class="form-error"></div><div class="form-actions"><button class="btn primary" type="submit" ${!classes.length?'disabled':''}>Confirmar turma e abrir agenda ${icon('arrow')}</button></div></form>`);}
function editEntity(entity,id,classId){if(!schemas[entity])return;const old=id?state.data[entity].find(row=>row.id===id):{};if(id&&!old)throw new Error('O registro não está mais disponível. Atualize a tela.');const record={...old};if(!id){if(entity==='classes')record.period_id=state.periodId;if(entity==='meetings'){record.class_id=classId || state.data.classes.find(c=>c.period_id===state.periodId)?.id || '';const period=state.data.periods.find(p=>p.id===state.periodId);record.start_date=period?.start_date || '';record.end_date=period?.end_date || '';}}
  editing={entity,original:record};const modal=openModal(`${id?'Editar':'Cadastrar'} ${schemas[entity].singular}`,`<form id="entity-form"><div class="form-grid">${fieldsHTML(entity,record,state.data,state.session.user.role)}<div class="field full"><label for="edit-reason">Motivo do cadastro ou alteração *</label><textarea id="edit-reason" name="reason" required placeholder="Descreva a informação conferida e o motivo da alteração."></textarea></div></div><div class="form-error"></div><div class="form-actions">${button('Cancelar','close-modal','secondary')}<button type="submit" class="btn primary">Salvar cadastro</button></div></form>`);
  if(state.session.user.role==='coordinator'){for(const key of entity==='classes'?['course_id','period_id']:id?['class_id']:[]){const field=modal.querySelector(`[name="${key}"]`);if(field)field.disabled=true;}}
}
function reasonDialog(title,kind,data){openModal(title,`<form id="reason-form" data-kind="${kind}" data-payload="${esc(JSON.stringify(data))}"><p>${kind==='delete'?'O registro será inativado ou retirado do rascunho. O histórico e a versão publicada serão preservados.':kind==='archive'?'Esta versão deixará de aparecer como publicação ativa. O histórico será preservado.':'Registre a orientação para que a equipe compreenda esta decisão.'}</p><label class="field">Motivo *<textarea name="reason" required minlength="3"></textarea></label><div class="form-error"></div><div class="form-actions">${button('Cancelar','close-modal','secondary')}<button type="submit" class="btn primary">Confirmar</button></div></form>`);}
async function suggestions(id){const event=events(state).find(e=>e.id===id);const result=await request('/api/suggestions?meeting_id='+encodeURIComponent(id));const options=result.suggestions || [];openModal('Revisar sala e entender os motivos',`<h3>${esc(event?.class.code)} · ${esc(event?.start)}–${esc(event?.end)}</h3>${event?.allocation?.explanation?notice(event.allocation.explanation):''}<p class="mt">Apenas salas válidas são apresentadas. Maior adequação indica melhor atendimento às preferências.</p>${!options.length?notice((result.unallocated || []).find(p=>p.meeting_id===id)?.reasons?.join(' ') || 'Nenhuma sala válida. Confira capacidade, recursos, horários, disponibilidade e acessibilidade.','warning'):''}<form id="move-form" data-id="${esc(id)}">${options.map(option=>{const room=state.data.rooms.find(r=>r.id===option.room_id);return `<label class="selection-card"><input type="radio" name="room_id" required value="${esc(option.room_id)}" ${event?.room?.id===option.room_id?'checked':''}><span><h3>${esc(room?.code || option.room_id)} · ${esc(option.score)} / 100</h3><p>${esc(option.explanation)}</p></span></label>`;}).join('')}<label class="field-inline mt"><input type="checkbox" name="locked" checked>Preservar este ajuste em novas gerações</label><label class="field mt">Motivo da escolha *<textarea name="reason" required minlength="3"></textarea></label><div class="form-error"></div><div class="form-actions"><button class="btn primary" type="submit" ${!options.length?'disabled':''}>Validar e salvar ajuste</button></div></form>`);}
function weightsDialog(){const weights=state.data.settings.weights;openModal('Pesos de adequação',`<p>Pesos não negativos, com soma maior que zero. As restrições obrigatórias permanecem fixas.</p><form id="weights-form"><div class="form-grid">${[['capacity','Ocupação dos lugares'],['building','Prédio preferido'],['resources','Recursos desejáveis'],['stability','Estabilidade da sala']].map(([key,label])=>`<label class="field">${label}<input type="number" name="${key}" min="0" max="10000" step="0.1" required value="${esc(weights[key])}"></label>`).join('')}<label class="field full">Motivo *<textarea name="reason" required></textarea></label></div><div class="form-error"></div><div class="form-actions"><button class="btn primary" type="submit">Salvar critérios</button></div></form>`);}
function importDialog(){importReport=null;openModal('Importar dados com revisão',`<form id="import-form"><div class="form-grid"><label class="field full">Tipo de cadastro<select name="entity" id="import-entity">${Object.entries(schemas).map(([key,value])=>`<option value="${key}" ${key===state.entity?'selected':''}>${value.title}</option>`).join('')}</select></label><label class="field full">Arquivo CSV<input type="file" id="import-file" accept=".csv,text/csv"></label><label class="field full">Conteúdo do CSV *<textarea name="csv" id="csv-content" rows="8" required placeholder="Cole o conteúdo ou escolha um arquivo. Use os cabeçalhos do modelo CSV."></textarea></label></div><p class="muted">Limite de 1 MiB. Listas usam ponto e vírgula; coloque campos que contenham separadores entre aspas. Nenhum registro é gravado nesta etapa.</p><div class="form-error"></div><div class="form-actions">${button('Baixar modelo','csv-template','secondary')}<button class="btn primary" type="submit">Conferir prévia</button></div></form><div id="import-report"></div>`);}
function renderImportReport(){const r=importReport;const target=document.querySelector('#import-report');if(!target)return;target.innerHTML=`<section class="mt"><h3>Resultado da prévia</h3><div class="chips"><span class="pill good">${r.valid_count} válidos</span><span class="pill ${r.errors.length?'bad':''}">${r.errors.length} erros</span><span class="pill">${r.duplicates.length} duplicidades</span><span class="pill">${r.warnings.length} avisos</span></div>${r.errors.length?`<ul class="error-list">${r.errors.map(e=>`<li>Linha ${esc(e.line)} · ${esc(e.field)}: ${esc(e.message)}</li>`).join('')}</ul>`:notice('Prévia válida. Confirme somente após revisar os registros.')}${r.records.length?`<details><summary>Revisar registros válidos</summary><pre>${esc(JSON.stringify(r.records,null,2))}</pre></details>`:''}<div class="control-row mt">${button('Baixar relatório','import-report','secondary')}${button('Confirmar importação','confirm-import','primary',!r.token||r.errors.length?'disabled':'')}</div></section>`;}
function csvTemplate(){const entity=document.querySelector('#import-entity')?.value || state.entity;const fields=['id',...schemas[entity].fields.map(f=>f.key)];download(`modelo-${entity}.csv`,fields.join(',')+'\r\n','text/csv;charset=utf-8');}
async function reviewPublication(){const [validation,comparison]=await Promise.all([request('/api/validate',{method:'POST',body:{period_id:state.periodId}}),request('/api/compare?period_id='+encodeURIComponent(state.periodId))]);state.validation=validation;state.comparison=comparison;render();}
async function exportCalendar(){if(state.demo){toast('A exportação usa uma sessão real na aplicação conectada. O exemplo público é somente consulta.');return;}const params=new URLSearchParams({period_id:state.periodId,date:state.date,view:'week'});if(state.classId)params.set('class_id',state.classId);const response=await fetch(`${API_BASE}/api/calendar.ics?${params}`,{credentials:'include',cache:'no-store'});if(!response.ok)throw new Error('Não foi possível exportar a agenda. Atualize sua sessão.');download('agenda.ics',await response.text(),'text/calendar;charset=utf-8');}

document.addEventListener('click',async event=>{if(event.target.closest('.skip-link')){event.preventDefault();const main=document.querySelector('#main');main?.setAttribute('tabindex','-1');main?.focus();return;}const target=event.target.closest('[data-action]');if(!target || target.disabled)return;const action=target.dataset.action;try{
  if(action==='close-modal'){closeModal();return;}if(action==='menu'){const open=document.querySelector('#sidebar').classList.toggle('open');target.setAttribute('aria-expanded',String(open));return;}
  if(action==='demo'){state.demo=true;state.session={user:{id:'public-example',name:'Visitante',role:'student',email:''},providers:{}};state.data=demoData();state.periodId=state.data.periods[0].id;state.classId=readPreference();if(!classesForPeriod().some(c=>c.id===state.classId))state.classId=state.data.classes[0].id;state.date=DEMO_DATE;state.loadedAt=new Date().toISOString();navigate('schedule');return;}
  if(action==='oauth'){location.assign(`${API_BASE}/auth/${encodeURIComponent(target.dataset.provider)}`);return;}
  if(action==='dev-login'){state.session=await request('/api/dev-login',{method:'POST',body:{role:target.dataset.role}});state.demo=false;state.periodId='';state.data=null;await loadData();navigate(target.dataset.role==='admin'?'allocation':target.dataset.role==='coordinator'?'coordinator':'schedule');return;}
  if(action==='logout'){if(!state.demo)await request('/api/logout',{method:'POST',body:{}});state.demo=false;state.data=null;state.periodId='';state.classId='';state.validation=null;state.comparison=null;state.session=API_BASE?await request('/api/session'):null;navigate('login');return;}
  if(action==='refresh'){state.validation=null;state.comparison=null;await loadData({quiet:true});toast('Consulta atualizada.');return;}
  if(action==='room'){openModal('Localização da sala',roomDetail(state,target.dataset.id));return;}
  if(action==='event'){openModal('Detalhes do encontro',eventDetail(state,target.dataset.id));return;}
  if(action==='choose-class'){chooseClass();return;}
  if(action==='schedule-view'){state.scheduleView=target.dataset.view;render();return;}
  if(action==='today'){state.date=state.demo?DEMO_DATE:localDate();render();return;}
  if(action==='print'){window.print();return;}
  if(action==='export-calendar'){await exportCalendar();return;}
  if(action==='entity-tab'){state.entity=target.dataset.entity;state.query='';render();return;}
  if(action==='edit-entity'){editEntity(target.dataset.entity,target.dataset.id,target.dataset.classId);return;}
  if(action==='delete-entity'){reasonDialog('Confirmar inativação','delete',{entity:target.dataset.entity,id:target.dataset.id});return;}
  if(action==='archive-version'){reasonDialog('Arquivar versão publicada','archive',{id:target.dataset.id});return;}
  if(action==='class-transition'){reasonDialog({submit:'Enviar necessidades',return:'Devolver pedido para revisão',approve:'Aprovar necessidades'}[target.dataset.transition],'transition',{id:target.dataset.id,transition:target.dataset.transition});return;}
  if(action==='add-block'){target.previousElementSibling.insertAdjacentHTML('beforeend',blockHTML({},target.dataset.field));return;}
  if(action==='remove-block'){target.closest('[data-block]').remove();return;}
  if(action==='weights'){weightsDialog();return;}
  if(action==='suggestions'){await suggestions(target.dataset.id);return;}
  if(action==='allocate'){target.disabled=true;const result=await mutate('/api/allocate',{period_id:state.periodId,...(state.selectedMeetings.size?{selected_meeting_ids:[...state.selectedMeetings]}:{})});state.solverResult=result;state.validation=result;render();toast('Proposta gerada. Revise as escolhas antes de publicar.');return;}
  if(action==='validate'){state.validation=await request('/api/validate',{method:'POST',body:{period_id:state.periodId}});render();return;}
  if(action==='review-publication'){await reviewPublication();return;}
  if(action==='import'){importDialog();return;}
  if(action==='csv-template'){csvTemplate();return;}
  if(action==='import-report'){download('relatorio-importacao.csv','linha,campo,motivo\r\n'+[...(importReport?.errors || []),...(importReport?.warnings || [])].map(e=>[e.line,e.field,e.message].map(v=>'"'+String(v ?? '').replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv;charset=utf-8');return;}
  if(action==='confirm-import'){target.disabled=true;const result=await mutate('/api/import/confirm',{token:importReport.token,reason:'Importação revisada e confirmada na interface.'});closeModal();toast(`${result.imported} registros importados.`);return;}
}catch(error){toast(error.message || String(error),true);if(error.status===409)await loadData({quiet:true});if(target.isConnected)target.disabled=false;}});

document.addEventListener('submit',async event=>{const form=event.target;if(!form.id || !['choose-class-form','entity-form','reason-form','move-form','weights-form','publish-form','import-form'].includes(form.id))return;event.preventDefault();const submit=form.querySelector('[type="submit"]');if(submit)submit.disabled=true;try{const data=new FormData(form);
  if(form.id==='choose-class-form'){const id=data.get('class_id');if(!classesForPeriod().some(c=>c.id===id))throw new Error('Selecione uma turma ativa.');savePreference(id);closeModal();navigate('schedule');render();toast('Turma confirmada.');}
  if(form.id==='entity-form'){const record=parseRecord(form,editing.entity,editing.original,state.session.user.role);await mutate('/api/entities/'+editing.entity,{record,reason:data.get('reason')});closeModal();toast('Cadastro salvo. A versão publicada foi preservada.');}
  if(form.id==='reason-form'){const payload=JSON.parse(form.dataset.payload);const reason=data.get('reason');if(form.dataset.kind==='delete'){await request(`/api/entities/${payload.entity}/${encodeURIComponent(payload.id)}`,{method:'DELETE',body:{revision:state.data.revision,reason}});state.validation=null;state.comparison=null;await loadData({quiet:true});}else if(form.dataset.kind==='archive')await mutate(`/api/versions/${encodeURIComponent(payload.id)}/archive`,{reason});else await mutate(`/api/classes/${encodeURIComponent(payload.id)}/${payload.transition}`,{reason});closeModal();toast('Decisão registrada no histórico.');}
  if(form.id==='move-form'){await mutate('/api/move',{meeting_id:form.dataset.id,room_id:data.get('room_id'),locked:data.has('locked'),reason:data.get('reason')});closeModal();toast('Ajuste salvo no rascunho. Publique uma revisão para torná-lo oficial.');}
  if(form.id==='weights-form'){const weights=Object.fromEntries(['capacity','building','resources','stability'].map(key=>[key,Number(data.get(key))]));if(Object.values(weights).reduce((a,b)=>a+b,0)<=0)throw new Error('Ao menos um peso precisa ser positivo.');await mutate('/api/weights',{weights,reason:data.get('reason')});closeModal();toast('Critérios atualizados.');}
  if(form.id==='publish-form'){await mutate('/api/publish',{period_id:state.periodId,description:data.get('description'),reason:data.get('reason')});toast('Versão oficial publicada.');navigate('history');}
  if(form.id==='import-form'){importReport=await request('/api/import/preview',{method:'POST',body:{entity:data.get('entity'),csv:data.get('csv')}});renderImportReport();}
}catch(error){if(error.details?.conflicts){state.validation=error.details;}formError(form,error);if(error.status===409){closeModal();await loadData({quiet:true});toast('Os dados mudaram. Abra novamente o registro atualizado antes de editar.',true);}}finally{if(submit?.isConnected)submit.disabled=false;}});

document.addEventListener('change',async event=>{const target=event.target;try{
  if(target.id==='period-select'){state.periodId=target.value;state.classId='';state.validation=null;state.comparison=null;state.selectedMeetings.clear();await loadData();}
  if(target.id==='schedule-date'){state.date=target.value || localDate();render();}
  if(target.id==='allocation-filter'){state.allocFilter=target.value;render();}
  if(target.id==='allocation-course'){state.allocCourse=target.value;render();}
  if(target.dataset.meetingSelect){target.checked?state.selectedMeetings.add(target.dataset.meetingSelect):state.selectedMeetings.delete(target.dataset.meetingSelect);render();}
  if(target.id==='select-all-meetings'){for(const checkbox of document.querySelectorAll('[data-meeting-select]'))target.checked?state.selectedMeetings.add(checkbox.dataset.meetingSelect):state.selectedMeetings.delete(checkbox.dataset.meetingSelect);render();}
  if(target.id==='import-file'){const file=target.files[0];if(file){if(file.size>1024*1024)throw new Error('O arquivo deve ter até 1 MiB.');document.querySelector('#csv-content').value=await file.text();importReport=null;document.querySelector('#import-report').innerHTML='';}}
}catch(error){toast(error.message,true);}});
document.addEventListener('input',event=>{const target=event.target;if(target.closest('#publish-form'))target.closest('form').dataset.dirty='true';if(target.id==='page-search'){const cursor=target.selectionStart;state.query=target.value;render();const field=document.querySelector('#page-search');field?.focus();try{field?.setSelectionRange(cursor,cursor);}catch{}}
  if(target.id==='class-search'){const q=target.value.toLocaleLowerCase('pt-BR');let count=0;for(const option of document.querySelectorAll('[data-class-option]')){option.hidden=!option.dataset.search.includes(q);if(!option.hidden)count++;}document.querySelector('#class-search-empty').hidden=count>0;}
  if(target.closest('#import-form') && importReport){importReport=null;document.querySelector('#import-report').innerHTML='';}
});
window.addEventListener('hashchange',async()=>{state.query='';if(state.session?.user?.role==='coordinator'&&state.data&&((state.data.mode==='published')!==needsOfficial())){await loadData({quiet:true});}else render();document.querySelector('#main')?.focus({preventScroll:true});});
async function revalidate(){if(!state.session?.user||state.demo||document.hidden||document.querySelector('#modal')?.open||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(document.querySelector('#publish-form')?.dataset.dirty)return;await loadData({quiet:true});}
window.addEventListener('focus',revalidate);setInterval(revalidate,60000);
async function start(){try{state.session=API_BASE?await request('/api/session'):null;if(state.session?.user)await loadData();else render();}catch(error){state.loginError=error.message;render();}}
start();
