/* Conjunto exclusivamente fictício, público e estático. Não representa sessão,
   autenticação, matrícula, publicação institucional ou execução do núcleo. */
export const DEMO_DATE='2026-09-29';
export const DEMO_MINUTES=19*60;
export function demoData(){return {
  revision:0,mode:'published',user:{id:'example-only',name:'Visitante',email:'',role:'student'},
  periods:[{id:'demo-period',code:'2026.2',name:'2026 · 2º semestre',start_date:'2026-08-03',end_date:'2026-12-18',active:true}],
  campuses:[{id:'demo-campus',code:'EX',name:'Campus de exemplo',address:'Endereço fictício para demonstração',directions:'Após a entrada principal, siga pela alameda central até o bloco indicado.'}],
  buildings:[{id:'demo-a',code:'A',name:'Bloco A · Ensino',campus_id:'demo-campus',directions:'Edifício à esquerda da alameda central. Entrada acessível no térreo.'},{id:'demo-b',code:'B',name:'Bloco B · Laboratórios',campus_id:'demo-campus',directions:'Edifício à direita da alameda central, em frente ao jardim. Elevador ao lado da recepção.'}],
  resources:[{id:'projector',code:'PROJ',name:'Projetor'},{id:'computers',code:'PC',name:'Computadores'},{id:'whiteboard',code:'LOUSA',name:'Lousa'}],
  courses:[{id:'demo-course',code:'ES',name:'Engenharia de Software',campus_id:'demo-campus'}],
  subjects:[{id:'demo-subj1',code:'DEV',name:'Desenvolvimento Web',course_id:'demo-course'},{id:'demo-subj2',code:'BD',name:'Banco de Dados',course_id:'demo-course'},{id:'demo-subj3',code:'ES',name:'Engenharia de Requisitos',course_id:'demo-course'}],
  rooms:[{id:'demo-room1',code:'A-204',name:'Sala de aula 204',campus_id:'demo-campus',building_id:'demo-a',floor:'2º andar',capacity:45,resources:['projector','whiteboard'],accessible:true,status:'active',directions:'Entre pela recepção do Bloco A. Suba ao 2º andar pelo elevador ou escada. Siga à direita; sala 204, quarta porta.',unavailable:[]},{id:'demo-room2',code:'B-102',name:'Laboratório de informática',campus_id:'demo-campus',building_id:'demo-b',floor:'1º andar',capacity:35,resources:['computers','projector','whiteboard'],accessible:true,status:'active',directions:'Entre pelo acesso principal do Bloco B. Use o elevador para o 1º andar. O laboratório 102 fica à esquerda.',unavailable:[]},{id:'demo-room3',code:'A-103',name:'Sala de aula 103',campus_id:'demo-campus',building_id:'demo-a',floor:'1º andar',capacity:40,resources:['projector','whiteboard'],accessible:true,status:'active',directions:'No Bloco A, suba ao 1º andar. Siga pelo corredor central até a sala 103.',unavailable:[]}],
  classes:[{id:'demo-class1',code:'ES-4N',name:'Engenharia de Software · 4º período',course_id:'demo-course',subject_id:'demo-subj1',period_id:'demo-period',size_expected:32,size_confirmed:32,teacher_emails:['docente.exemplo@example.org'],campus_id:'demo-campus',required_resources:['projector'],preferred_resources:[],needs_accessibility:true,shift:'Noturno',status:'approved'},{id:'demo-class2',code:'ES-2N',name:'Engenharia de Software · 2º período',course_id:'demo-course',subject_id:'demo-subj2',period_id:'demo-period',size_expected:28,size_confirmed:28,teacher_emails:['professor.exemplo@example.org'],campus_id:'demo-campus',required_resources:['computers'],preferred_resources:[],needs_accessibility:false,shift:'Noturno',status:'approved'}],
  meetings:[{id:'demo-m1',class_id:'demo-class1',weekday:1,start:'18:30',end:'20:10',start_date:'2026-08-03',end_date:'2026-12-18',date:null,excluded_dates:[]},{id:'demo-m2',class_id:'demo-class1',weekday:1,start:'20:30',end:'22:10',start_date:'2026-08-03',end_date:'2026-12-18',date:null,excluded_dates:[]},{id:'demo-m3',class_id:'demo-class1',weekday:0,start:'18:30',end:'20:10',start_date:'2026-08-03',end_date:'2026-12-18',date:null,excluded_dates:[]},{id:'demo-m4',class_id:'demo-class1',weekday:3,start:'18:30',end:'20:10',start_date:'2026-08-03',end_date:'2026-12-18',date:null,excluded_dates:[]},{id:'demo-m5',class_id:'demo-class1',weekday:4,start:'20:30',end:'22:10',start_date:'2026-08-03',end_date:'2026-12-18',date:null,excluded_dates:[]},{id:'demo-m6',class_id:'demo-class2',weekday:1,start:'18:30',end:'20:10',start_date:'2026-08-03',end_date:'2026-12-18',date:null,excluded_dates:[]}],
  allocations:[{meeting_id:'demo-m1',room_id:'demo-room1',source:'automatic',locked:false},{meeting_id:'demo-m2',room_id:'demo-room2',source:'manual',locked:true,changed:true,change_reason:'Laboratório reservado para a atividade prática.'},{meeting_id:'demo-m3',room_id:'demo-room3',source:'automatic'},{meeting_id:'demo-m4',room_id:'demo-room2',source:'automatic'},{meeting_id:'demo-m5',room_id:'demo-room1',source:'automatic'},{meeting_id:'demo-m6',room_id:'demo-room2',source:'automatic'}],
  published_version:{id:'example-v2',number:2,published_at:'2026-09-29T16:40:00-03:00',description:'Exemplo fictício: ajuste de laboratório.',author:'Administração de exemplo',changes:[{meeting_id:'demo-m2',kind:'changed',before:{room_id:'demo-room3'},after:{room_id:'demo-room2'},reason:'Laboratório reservado para a atividade prática.'}]},
  settings:{weights:{capacity:1,building:1,resources:1,stability:1}},versions:[],audit:[],users:[]
};}
