import {esc,weekdays,list} from './ui.js';
const f=(key,label,type='text',options={})=>({key,label,type,...options});
export const schemas={
  periods:{title:'Períodos',singular:'período letivo',fields:[f('code','Código','text',{required:true}),f('name','Nome','text',{required:true}),f('start_date','Início','date',{required:true}),f('end_date','Término','date',{required:true}),f('submission_deadline','Prazo para envio das necessidades','date'),f('active','Período ativo','boolean',{default:true})]},
  campuses:{title:'Campi',singular:'campus',fields:[f('code','Código','text',{required:true}),f('name','Nome','text',{required:true}),f('address','Endereço completo','text',{full:true}),f('directions','Como chegar','textarea',{full:true})]},
  buildings:{title:'Prédios',singular:'prédio',fields:[f('code','Código','text',{required:true}),f('name','Nome','text',{required:true}),f('campus_id','Campus','ref',{ref:'campuses',required:true}),f('directions','Localização e acesso','textarea',{full:true})]},
  resources:{title:'Recursos',singular:'recurso',fields:[f('code','Código','text',{required:true}),f('name','Nome','text',{required:true})]},
  courses:{title:'Cursos',singular:'curso',fields:[f('code','Código','text',{required:true}),f('name','Nome','text',{required:true}),f('campus_id','Campus','ref',{ref:'campuses',required:true})]},
  subjects:{title:'Disciplinas',singular:'disciplina',fields:[f('code','Código','text',{required:true}),f('name','Nome','text',{required:true}),f('course_id','Curso','ref',{ref:'courses',required:true})]},
  rooms:{title:'Salas',singular:'sala',fields:[f('code','Código da sala','text',{required:true}),f('name','Nome','text',{required:true}),f('campus_id','Campus','ref',{ref:'campuses',required:true}),f('building_id','Prédio','ref',{ref:'buildings',required:true}),f('floor','Andar','text',{required:true,placeholder:'Térreo, 1º andar…'}),f('capacity','Capacidade','number',{required:true,min:1,max:10000}),f('exam_capacity','Capacidade em provas','number',{min:1,max:10000}),f('type','Tipo de espaço','text',{placeholder:'Sala de aula, laboratório…'}),f('status','Disponibilidade','select',{options:[['active','Ativa'],['maintenance','Em manutenção'],['inactive','Inativa']],default:'active'}),f('accessible','Acesso adequado às necessidades de acessibilidade','boolean',{default:false}),f('resources','Recursos disponíveis','multi',{ref:'resources',full:true}),f('directions','Instruções para localizar a sala','textarea',{full:true}),f('available','Horários de funcionamento','blocks',{full:true,help:'Sem intervalos, a sala é considerada aberta. Se informar intervalos, todas as aulas precisam caber neles.'}),f('unavailable','Indisponibilidades','blocks',{full:true,help:'Uma indisponibilidade sempre bloqueia a sala, mesmo dentro do horário de funcionamento.'})]},
  users:{title:'Pessoas e acesso',singular:'pessoa autorizada',fields:[f('email','E-mail autorizado','email',{required:true}),f('name','Nome','text',{required:true}),f('role','Papel','select',{required:true,options:[['student','Aluno'],['teacher','Professor'],['coordinator','Coordenador'],['admin','Administrador']]}),f('active','Acesso ativo','boolean',{default:true}),f('course_ids','Cursos sob responsabilidade (coordenação)','multi',{ref:'courses',full:true})]},
  classes:{title:'Turmas',singular:'turma',fields:[f('code','Código da turma','text',{required:true}),f('name','Nome da turma','text',{required:true}),f('course_id','Curso','ref',{ref:'courses',required:true}),f('subject_id','Disciplina','ref',{ref:'subjects',required:true}),f('period_id','Período letivo','ref',{ref:'periods',required:true}),f('campus_id','Campus obrigatório','ref',{ref:'campuses',required:true}),f('shift','Turno','select',{options:[['Matutino','Matutino'],['Vespertino','Vespertino'],['Noturno','Noturno'],['Integral','Integral']]}),f('size_expected','Estudantes previstos','number',{required:true,min:1,max:10000}),f('size_confirmed','Estudantes confirmados','number',{min:1,max:10000}),f('teacher_emails','E-mails dos professores','list',{required:true,full:true,help:'Separe por ponto e vírgula. Os professores devem estar pré-cadastrados.'}),f('needs_accessibility','Acessibilidade obrigatória','boolean'),f('preferred_building_id','Prédio preferencial','ref',{ref:'buildings'}),f('required_resources','Recursos obrigatórios','multi',{ref:'resources',full:true}),f('preferred_resources','Recursos desejáveis','multi',{ref:'resources',full:true}),f('special_justification','Justificativa das necessidades e preferências','textarea',{full:true}),f('status','Estado','select',{adminOnly:true,options:[['draft','Rascunho'],['submitted','Enviada'],['in_review','Em revisão'],['approved','Aprovada'],['cancelled','Cancelada'],['closed','Encerrada']],default:'draft'})]},
  meetings:{title:'Encontros',singular:'encontro',fields:[f('class_id','Turma','ref',{ref:'classes',required:true}),f('weekday','Dia da semana','select',{options:weekdays.map((v,i)=>[i,v]),numeric:true,default:0}),f('start','Hora inicial','time',{required:true}),f('end','Hora final','time',{required:true}),f('date','Data excepcional (opcional)','date',{help:'Preencha somente para um encontro em data única.'}),f('start_date','Início da recorrência','date',{required:true}),f('end_date','Fim da recorrência','date',{required:true}),f('excluded_dates','Datas sem aula','list',{full:true,help:'Datas no formato AAAA-MM-DD, separadas por ponto e vírgula.'})]},
};
export const labelOf=record=>[record.code,record.name || record.email].filter(Boolean).join(' · ') || record.id;
export function fieldsHTML(entity,record,data,role){return schemas[entity].fields.filter(field=>!field.adminOnly || role==='admin').map(field=>{
  const value=record[field.key] ?? field.default ?? '';
  const attributes=`name="${esc(field.key)}" id="field-${esc(field.key)}" ${field.required?'required':''} ${field.min!==undefined?`min="${field.min}"`:''} ${field.max!==undefined?`max="${field.max}"`:''} ${field.placeholder?`placeholder="${esc(field.placeholder)}"`:''}`;
  let input='';
  if(field.type==='boolean')return `<div class="field ${field.full?'full':''}"><label class="field-inline" for="field-${esc(field.key)}"><input type="checkbox" ${attributes} ${value?'checked':''}> ${esc(field.label)}</label></div>`;
  if(field.type==='multi')input=`<div class="chips">${(data[field.ref] || []).map(row=>`<label class="field-inline"><input type="checkbox" name="${esc(field.key)}" value="${esc(row.id)}" ${list(value).includes(row.id)?'checked':''}>${esc(row.name || row.code)}</label>`).join('') || '<small>Ainda não há opções cadastradas.</small>'}</div>`;
  else if(field.type==='blocks')input=`<div data-blocks="${field.key}">${(Array.isArray(value)?value:[]).map(block=>blockHTML(block,field.key)).join('')}</div><button type="button" class="btn secondary small" data-action="add-block" data-field="${field.key}">Adicionar intervalo</button>`;
  else if(field.type==='ref' || field.type==='select')input=`<select ${attributes}><option value="">Selecione…</option>${(field.type==='ref'?(data[field.ref] || []).map(row=>[row.id,labelOf(row)]):field.options).map(([key,label])=>`<option value="${esc(key)}" ${String(value)===String(key)?'selected':''}>${esc(label)}</option>`).join('')}</select>`;
  else if(field.type==='textarea')input=`<textarea ${attributes}>${esc(value)}</textarea>`;
  else input=`<input type="${field.type==='list'?'text':field.type}" ${attributes} value="${esc(field.type==='list'?list(value).join('; '):value)}">`;
  return `<div class="field ${field.full?'full':''}"><label for="field-${esc(field.key)}">${esc(field.label)}${field.required?' *':''}</label>${input}${field.help?`<small>${esc(field.help)}</small>`:''}</div>`;
}).join('');}
export function blockHTML(block={},field='unavailable'){return `<fieldset class="mb" data-block data-field="${esc(field)}"><legend>Intervalo de ${field==='available'?'funcionamento':'indisponibilidade'}</legend><div class="form-grid"><label class="field">Data única (opcional)<input type="date" data-block-date value="${esc(block.date)}"></label><label class="field">Ou dia recorrente<select data-block-weekday><option value="">Sem recorrência</option>${weekdays.map((day,i)=>`<option value="${i}" ${String(block.weekday)===String(i)?'selected':''}>${day}</option>`).join('')}</select></label><label class="field">Vigência inicial da recorrência<input type="date" data-block-first value="${esc(block.start_date)}"></label><label class="field">Vigência final da recorrência<input type="date" data-block-last value="${esc(block.end_date)}"></label><label class="field">De<input type="time" data-block-start required value="${esc(block.start)}"></label><label class="field">Até<input type="time" data-block-end required value="${esc(block.end)}"></label></div><div class="mt"><button type="button" class="btn danger small" data-action="remove-block">Remover intervalo</button></div></fieldset>`;}
export function parseRecord(form,entity,original,role){const data=new FormData(form);const record={...original};
  for(const field of schemas[entity].fields){if(field.adminOnly && role!=='admin')continue;if(form.querySelector(`[name="${field.key}"]`)?.disabled)continue;
    if(field.type==='boolean'){record[field.key]=data.has(field.key);continue;}
    if(field.type==='multi'){record[field.key]=data.getAll(field.key);continue;}
    if(field.type==='blocks'){record[field.key]=[...form.querySelectorAll(`[data-blocks="${field.key}"] [data-block]`)].map(row=>{const date=row.querySelector('[data-block-date]').value;const start=row.querySelector('[data-block-start]').value;const end=row.querySelector('[data-block-end]').value;if(start>=end)throw new Error('A hora final do intervalo deve ser posterior à inicial.');if(date)return {date,start,end};const weekday=row.querySelector('[data-block-weekday]').value;const first=row.querySelector('[data-block-first]').value;const last=row.querySelector('[data-block-last]').value;if(weekday===''||!first||!last||first>last)throw new Error('Informe uma data única ou um dia semanal com vigência inicial e final válidas.');return {weekday:Number(weekday),start_date:first,end_date:last,start,end};});continue;}
    let value=String(data.get(field.key) || '').trim();
    if(field.type==='list')value=list(value);
    else if(field.type==='number' || field.numeric)value=value===''?null:Number(value);
    else if(value==='' && ['date','ref'].includes(field.type))value=null;
    record[field.key]=value;
  }
  if(record.start && record.end && record.start>=record.end)throw new Error('A hora final deve ser posterior à hora inicial.');
  if(record.start_date && record.end_date && record.start_date>record.end_date)throw new Error('A data final deve ser posterior ou igual à data inicial.');
  if(record.teacher_emails?.some(email=>!/^\S+@\S+\.\S+$/.test(email)))throw new Error('Informe um e-mail válido para cada professor.');
  if(record.excluded_dates?.some(date=>!/^\d{4}-\d{2}-\d{2}$/.test(date)))throw new Error('Use AAAA-MM-DD nas datas sem aula.');
  return record;
}
